spring:
  security:
    user:
      name: test
      password: 1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobilele?createDatabaseIfNotExist=yes&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    schemas: mobilele
    user: root
    password: root
    locations: classpath:db.migration
    baseline-on-migrate: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mail:
  host: "localhost"
  port: 1025
  username: "mobilele@mobilele.com"
  password: ""

mobilele:
  admin:
    defaultpass: ${DEFAULT_PASS:test}